// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtIqEpaOSKvFYAgSqTpzCIW4eAk28RFXg',
    appId: '1:83333785148:web:22fa43aabd7d68f6d20539',
    messagingSenderId: '83333785148',
    projectId: 'flyai-org',
    authDomain: 'flyai-org.firebaseapp.com',
    storageBucket: 'flyai-org.firebasestorage.app',
    measurementId: 'G-LQY5SYXY0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGZmLguHdnH9IZ7yCNQ_hauzGtC8HYcLE',
    appId: '1:83333785148:android:b837a5210a5587fad20539',
    messagingSenderId: '83333785148',
    projectId: 'flyai-org',
    storageBucket: 'flyai-org.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQiZxI6kBpVOFvUj25Si4q0LoC2XzuKRw',
    appId: '1:83333785148:ios:5328500fca12019ad20539',
    messagingSenderId: '83333785148',
    projectId: 'flyai-org',
    storageBucket: 'flyai-org.firebasestorage.app',
    iosClientId: '83333785148-shi86uh6js5q8kgto0vddfrho1lodgdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flyai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQiZxI6kBpVOFvUj25Si4q0LoC2XzuKRw',
    appId: '1:83333785148:ios:5328500fca12019ad20539',
    messagingSenderId: '83333785148',
    projectId: 'flyai-org',
    storageBucket: 'flyai-org.firebasestorage.app',
    iosClientId: '83333785148-shi86uh6js5q8kgto0vddfrho1lodgdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flyai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtIqEpaOSKvFYAgSqTpzCIW4eAk28RFXg',
    appId: '1:83333785148:web:27e627b8705e971cd20539',
    messagingSenderId: '83333785148',
    projectId: 'flyai-org',
    authDomain: 'flyai-org.firebaseapp.com',
    storageBucket: 'flyai-org.firebasestorage.app',
    measurementId: 'G-40RH4NKHHZ',
  );
}
